### ISSUE TITLE
Incompatible with later TF versions

### ISSUE THREAD

**Issue by emielzyde** [HareeshBahuleyan/probabilistic_nlg#1]
The '_compute_output_shape' function in the BasicDecoder function is not compatible with later versions of TensorFlow. What should I replace it by to make it compatible?

**Comment by HareeshBahuleyan** [comment]
@misterzyde 
I believe that the newer version of tensorflow uses `compute_output_shape` instead (no underscore).
Refer [here](https://github.com/tensorflow/tensorflow/blob/c407b045b8802f9eded430ef48be18cd85e4788c/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py#L91).

**Comment by emielzyde** [comment]
That works, thank you! :)
